[project]
name = "htmldocx"
version = "0.0.6"

dependencies = [
  "beautifulsoup4 == 4.8.0",
  "python-docx == 0.8.11"
]

requires-python = ">= 3.7"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
